version: '3.1'

services:
  owncloud:
    image: owncloud
    container_name: owncloud_app
    restart: always
    ports:
      - 80:80
    volumes:
      - ./apps:/var/www/html/apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data

  mysql:
    image: mariadb:latest
    container_name: owncloud_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dxmonkey
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=owncloud
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: owncloud_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql_data: